### ISSUE TITLE
asdf error (slot-unbound) when building my documentation

### ISSUE THREAD

**Issue by vindarel** [gwkkwg/tinaa#6]
Hi,

This projects looks interesting, though I can't build the doc for my project given an asdf error:

```
(tinaa:document-system :package :BOOKSHOPS #p"tinaa-docs/")
When attempting to
test to see whether slot is bound (SLOT-BOUNDP), the slot
ASDF/COMPONENT:COMPONENTS is missing from the object
#<ASDF/SYSTEM:SYSTEM "tinaa">.
```

I'm on ASDF 3.3, SBCL 1.2.4.

Looking forward for some progress… and a README !

**Comment by gwkkwg** [comment]
Hi Vindarel,

I'm sorry that Tinaa isn't working with SBCL. I'm not able to maintain this project anymore and would suggest you look at some of the myriad of other CL documentation tools.
